### PR TITLE
Add VeShawties collection

### PR DESCRIPTION
**Pull request by Scale0**
The presale will start on the 8th of March 2022 at 12:00 pm UTC +0
The public sale will start on the 8th of March 2022 at 18:00 pm UTC +0

I know its really short day, connect button didnt work yet and there was an issue reaching the devleoper, didnt wanna PR a non working dApp :)

### CODE REVIEW

**Comment by XJWX89** [comment]
hi @Scale0 ,thanks for the submission . please let me know when it is ready . moreover, It seems that the the website certificate is not valid when I try to visit the link you provided. please confirm with the dev

**Comment by Scale0** [comment]
hi @XJWX89 , thanks for your feedback, did you get a invalid certificate error? me and @Murtagh300 are not getting that error.. all other issues were resolved before submit :)

**Review by XJWX89 — APPROVED** [review]

**Comment by XJWX89** [comment]
> hi @XJWX89 , thanks for your feedback, did you get a invalid certificate error? me and @Murtagh300 are not getting that error.. all other issues were resolved before submit :)

yea.... I got the error this morning , but it seems all good now.

**Comment by Murtagh300** [comment]
@XJWX89 Mint will open up in 2 hours. Will the Dapp be visible by then ?

**Pull request merged**
