### PR TITLE
PepePlug

### PR DESCRIPTION
**Pull request by WildBillDev**
Helping do PW for Murtugh

### CODE REVIEW

**Comment by Murtagh300** [comment]
@libotony Before any Doubts, @WildBillDev Is helping me around with Pull Requests for Turtlel Labs etc.

**Comment by libotony** [comment]
@WildBillDev Could update your branch with `vechain/master`?

**Comment by WildBillArt** [comment]
okay guys i am not sure what i am doing wrong its all showing its just waiting for approval with green checks 
im not seeing a update branch setting for this pull request

**Comment by WildBillArt** [comment]
Should be synced now @libotony

**Comment by libotony** [comment]
> Should be synced now @libotony

I'm afraid there are no commits appended,  please verify.

**Comment by WildBillDev** [comment]
I don't even want to say what i did wrong lol but that looks like its fixed and i have committed to master everything but the pp changes. @libotony

**Review by libotony — APPROVED** [review]

**Pull request merged**
