### PR TITLE
Update promote list to include VeSea

### PR DESCRIPTION
**Pull request by VeSeaOfficial**
Adding VeSea as a promoted dApp. Hope is to have a single location linked on main discover to avoid the numerous dApps for individual projects being launched.

### CODE REVIEW

**Comment by Bread-VeSea** [comment]
@XJWX89 @libotony 

Checking in here as it's been a couple of months. Is something required to be included?

**Review by XJWX89 — APPROVED** [review]
@libotony , According to GA event tracking report(last `60`&`30` days), Vesea has high popularity in the ecosystem, I think Vesea deserves to be added to the promotion list.

**Comment by libotony** [comment]
LGTM, I'll check the script and merge this PR ASAP @XJWX89 @VeSeaOfficial  @Bread-VeSea .

**Comment by Bread-VeSea** [comment]
Thanks guys. Let me know if anything else is needed from me.

**Pull request merged**
