### PR TITLE
Merge Turtle Swap

### PR DESCRIPTION
**Pull request by Murtagh300**

### CODE REVIEW

**Comment by Murtagh300** [comment]
@libotony @darrenvechain can you please check

**Comment by libotony** [comment]
@Murtagh300 Recently we have added a new field `isVeWorldSupported`, could kindly add that into your file? Thanks!

> isVeWorldSupported is required, set this to true if your dApp supports the VeWorld browser extension, enabling its use within the VeWorld mobile wallet. Your dApp will then be listed in the dApp section of the VeWorld mobile discovery.

**Comment by Murtagh300** [comment]
@libotony Is this correct now?

**Comment by libotony** [comment]
> @libotony Is this correct now?

No, put it into the JSON object. And please merge the master from vechain into your branch.

**Comment by Murtagh300** [comment]
@libotony I think i did it the right way now

**Review by libotony — APPROVED** [review]

**Pull request merged**
