### PR TITLE
add SafeSwap

### PR DESCRIPTION
**Pull request by andydemeulemeester**

### CODE REVIEW

**Comment by XJWX89** [comment]
hi @andydemeulemeester ,just wondering when safeswap go-live?

**Comment by andydemeulemeester** [comment]
> hi @andydemeulemeester ,just wondering when safeswap go-live?

The platform is ready. The audit is ongoing.
We expect a report this week or next week.

**Comment by XJWX89** [comment]
I see, is it support connex?

**Comment by andydemeulemeester** [comment]
> 

Yes it supports Sync2.

image

**Comment by XJWX89** [comment]
awesome! i will review this PR when it is ready for users. please keep us posted when the platform is ready to go-live.  

> Postponed - due to user cannot access the safeswap platform (audit is ongoing) @libotony

**Comment by andydemeulemeester** [comment]
SafeSwap platform is live @ [app.safeswap.io](https://app.safeswap.io)
See:
[https://safehaven.io/safe-haven-officially-welcomes-safeswap-to-the-product-suite/](https://safehaven.io/safe-haven-officially-welcomes-safeswap-to-the-product-suite/)
[https://twitter.com/safehavenio/status/1522621888530423808?s=21&t=qZA9B9Ys4PKjJxm8y7OWiQ](https://twitter.com/safehavenio/status/1522621888530423808?s=21&t=qZA9B9Ys4PKjJxm8y7OWiQ)

**Review by XJWX89 — APPROVED** [review]

**Comment by cortesdev** [comment]
It's evolution

**Pull request merged**
