### PR TITLE
feat: add isVeWorldSupported variable

### PR DESCRIPTION
**Pull request by davidecarpini**

### CODE REVIEW

**Comment by darrenvechain** [comment]
@davidecarpini instead of having a field `isVeWorldCompatible` could we introduce it as a tag instead? I know that introducing new fields could potentially break existing applications. Not Node JS, but Java/ Kotlin, probably others

**Comment by davidecarpini** [comment]
Hey @darrenvechain it's not a problem to move everything to a tag, but I think it's not a good idea since a tag is more a characteristic of the dapp, rather than a behavior. 
tbh if the code explodes because we add an attribute in the json it's probably not great code 😄 
said that, you are right and we should probably consider versioning it, in case we need to add/remove stuff in the future.
FYI: @libotony

**Comment by fabiofvc** [comment]
Connected to https://github.com/vechain/veworld-mobile/pull/1954

**Comment by libotony** [comment]
@davidecarpini Considering the deserialization for typed languages, what do you think making the field `isVeWorldSupported` required or normalizing it in the packing script?

**Comment by fabiofvc** [comment]
@davidecarpini considering we have different Wallets (Sync, Sync2, VechainThor, VeWorld) why don't we move to a structure like:
```
walletSupported: {
  sync: true,
  sync2: true,
  vechainthor: true,
  veworld: true
}
```
?

For VeWorld POV is overkill, I know.
However, the AppHub itself could provide more data and a new filtering feature (by wallet).

**Comment by davidecarpini** [comment]
@fabiofvc it's a good point, and normalizing the flag would be nice if in the future we aim to support multiple wallets. But I think we should keep just one wallet in the future, so it wouldn't make much sense in the long run.
BTW my POV on this flag is different, every newly accepted dapp should support veworld, it should be mandatory. This should be a retro compatibility flag that allows us to know which of these dapps is supporting veworld.  
I see this flag being deprecated in the long long run, where we can request updates from the dapps to support the wallet or we will remove them from the app-hub.

@libotony I added all missing dapps flags (the 'false' ones) and added the flag as required in the validation script and in the readme

**Comment by libotony** [comment]
> @fabiofvc it's a good point, and normalizing the flag would be nice if in the future we aim to support multiple wallets. But I think we should keep just one wallet in the future, so it wouldn't make much sense in the long run. BTW my POV on this flag is different, every newly accepted dapp should support veworld, it should be mandatory. This should be a retro compatibility flag that allows us to know which of these dapps is supporting veworld. I see this flag being deprecated in the long long run, where we can request updates from the dapps to support the wallet or we will remove them from the app-hub.
> 
> @libotony I added all missing dapps flags (the 'false' ones) and added the flag as required in the validation script and in the readme

Agree, that wallet flag might be overkilling. My understanding is it was for veworld checking dApp's compatiabilty.  It should be suggested that all dApps that supports the popular wallets.

**Review by libotony — APPROVED** [review]

**Pull request merged**
