### PR TITLE
Add nonerds Inc NFT collection

### PR DESCRIPTION
**Pull request by Scale0**
NFT Collection for non sellers!
Mint will happen on 27th of january.
Its not a big problem if its not merged before that date.

### CODE REVIEW

**Comment by XJWX89** [comment]
hi @Scale0 , there are two things I would like to confirm with you before approving this pr
1. It seems that the connex is connected to ***testnet*** ,  if it is a misconfiguration please change it to mainnet.
2. It is a little bit hard for the user to connect their wallet. is it possible to slightly improve the ux so that ppl can easily buy the tablet.

**Comment by Scale0** [comment]
Hi @XJWX89 ,
thank for your feedback,
i will get back to the developer, once i have confirmation i will comment it here :)

**Comment by Murtagh300** [comment]
Should be all fixxed now ! 🙌

**Comment by Scale0** [comment]
@XJWX89 as @Murtagh300 indeed said :) the developer fixxed them :)

**Review by XJWX89 — APPROVED** [review]

**Pull request merged**
