### PR TITLE
Initial commit of the VeThugs NFT dapp

### PR DESCRIPTION
**Pull request by Murtagh300**

### CODE REVIEW

**Comment by XJWX89** [comment]
hi @Murtagh300, thanks for submitted the application, just wondering when it goes live ?

**Comment by Murtagh300** [comment]
Presale will start on 11 december 2021  and public sale 12 december 2021, this will be added soon to our app

**Review by XJWX89 — APPROVED** [review]
thanks for the information @Murtagh300 

This PR merge will be postponed due to ensure the exposure for the public, will be merged no later than Dec.6.

if you wish to merge this PR right away, we do not guarantee your application exposure.Moreover, if the time of the pre-sale changed or any circumstance feel free to ping us.

**Comment by Murtagh300** [comment]
We would love to have it visable as soon as possible. We already distributed some Give Away VeThugs so it would be great if people could check it out already. Thanks for approving !

**Pull request merged**
