### PR TITLE
Add metaversials

### PR DESCRIPTION
**Pull request by Bread-VeSea**
Initial commit for dApp.

Go-Live: Feb 19th, 6pm
URL live: 2/17

### CODE REVIEW

**Comment by Bread-VeSea** [comment]
Hey @XJWX89,

Sending this as a reminder that tomorrow Metaversials will be going live. Please let me know if you need anything from me.

**Comment by Bread-VeSea** [comment]
Checking in again. Would like to get this merged before launch if possible (5hr)

@XJWX89 @libotony

**Comment by XJWX89** [comment]
sorry @Bread-VeSea for the late merge. your apps will be shown shortly.

**Comment by Bread-VeSea** [comment]
No worries, and we appreciate it.

**Pull request merged**
