### PR TITLE
Add NPO nft website

### PR DESCRIPTION
**Pull request by VeChaz**
Add New Pigs Order NFT website

- Website is not published yet but should be Tomorrow, I will update this PR when the site is live.

### CODE REVIEW

**Comment by VeChaz** [comment]
@XJWX89 - This is now live and I just updated the website URL since we changed it to www. 

This is hooked to main net and Connex is working so everything should be good to go. A few updated will be made but the public mint is Tomorrow so if we could get this approved and on the App Hub as soon as possible that would be appreciated and crucial.

Thank you as always!

**Comment by VeChaz** [comment]
@libotony - Just tagging you as well in case @XJWX89 isn't around. Thank you!

**Review by XJWX89 — APPROVED** [review]
hi @VeChaz , thanks for the update! before merging this pull request, i want to double check with  you about the amount that cost for the mint. 

**Please confirm the amount is correct to process the merge**

@libotony  ,please hold this PR and wait for the confirmation

**Comment by VeChaz** [comment]
> hi @VeChaz , thanks for the update! before merging this pull request, i want to double check with you about the amount that cost for the mint.
> 
> **Please confirm the amount is correct to process the merge**
> 
> @libotony ,please hold this PR and wait for the confirmation

Hey @XJWX89 @libotony - right now it's at now it is 0.000000001 VET for testing purposes but tomorrow at launch it will be 3,000 VET to mint.

Thanks!

**Comment by VeChaz** [comment]
> > hi @VeChaz , thanks for the update! before merging this pull request, i want to double check with you about the amount that cost for the mint.
> > **Please confirm the amount is correct to process the merge**
> > @libotony ,please hold this PR and wait for the confirmation
> 
> Hey @XJWX89 @libotony - right now it's at 0.000000001 VET for testing purposes but tonight before launch tomorrow it will be 3,000 VET to mint.
> 
> Thanks!

@libotony @XJWX89 - okay it's updated now with the final mint price of 3000 VET. Can you go ahead and merge this now? 

Thank you!

**Pull request merged**
