### PR TITLE
Add exoworlds

### PR DESCRIPTION
**Pull request by ExoworldsNFT**

### CODE REVIEW

**Comment by XJWX89** [comment]
hi @ExoworldsNFT , thanks for the changes! everything looks perfect now.  I just wondering when  the wallet Integration will be available?

**Comment by ExoworldsNFT** [comment]
Hi ShaoHuai @XJWX89! We're migrating to AWS and will have wallet integration by next friday. People are currently able to whitelist their address through a form already so wanted to see if we could get it added to the app hub already

**Comment by XJWX89** [comment]
@ExoworldsNFT  understood, thanks for the information . one last thing , as you mentioned that people are able to whitelist 
 their address through a form .but i click the **whitelist** on the top of the `https://www.exoworlds.io/` it seems that nothing happened.

**Comment by ExoworldsNFT** [comment]
Hi ShaoHuai @XJWX89 , the whitelist filled up quite fast and we reached the 360 applications 2 days after the form went online (https://twitter.com/exoworldsnft/status/1472239517486796807?s=21), the form is now offline again but will reopen for a new tier when we’re closer to the minting date!

**Review by XJWX89 — APPROVED** [review]
@ExoworldsNFT  thanks for the feedback.

**Comment by ExoworldsNFT** [comment]
@XJWX89 Yes you're completely right! I just fixed it so that it now anchors to the whitelist section where it explains the tier 2 whitelist is filled and tier 3 is opening at a TBA moment, thanks!

**Comment by libotony** [comment]
hi @ExoworldsNFT, according to the guideline, the application needs to support the connex. thus, I will merge this PR when the wallet integration is ready.

**Comment by ExoworldsNFT** [comment]
Hi @libotony, I'm sorry for the delay, the migration to AWS took a little longer since we didn't have everyone on board due to the holidays. I would like to wish you a happy new years! The wallet integration is now done and the new website is live. If it still shows a warning then that's a cache issue that will be fixed later today. Opening in private or a new browser should fix that :)

**Comment by ExoworldsNFT** [comment]
@XJWX89

**Pull request merged**
