### PR TITLE
Add bridge.vet

### PR DESCRIPTION
**Pull request by ifavo**
This PR contains bridge.vet as additional App and updates the description of vtho.exchange

### CODE REVIEW

**Comment by ifavo** [comment]
I see the validator mentions that the PR should only contain one app at a time. Should I split the text change into a second PR?

**Comment by libotony** [comment]
Would you mind 

> I see the validator mentions that the PR should only contain one app at a time. Should I split the text change into a second PR?

Yes please, the one application restriction comes first. Thank you!

**Comment by ifavo** [comment]
@libotony okay, thanks, removed the text change and will do a second PR 🙏

**Comment by ifavo** [comment]
@libotony sorry for the little mess, I've replaced this PR with https://github.com/vechain/app-hub/pull/286

**Pull request closed without merging**
